### ISSUE TITLE
Converting to html.erb

### ISSUE THREAD

**Issue by Louigi16** [yzgan-bookdoc/rails_6_bootstrap_template#4]
Hello, i'm trying to convert this template in html.erb. Everything seems to be working, except for this:

![github_issue](https://user-images.githubusercontent.com/44639196/83761429-98e94e80-a676-11ea-850b-78470d68d95b.jpg)

When i'm using application.html.erb i have this problem. Instead, when i'm using application.html.haml everything goes well.

These are my 2 application files:

![difference](https://user-images.githubusercontent.com/44639196/83763034-8839d800-a678-11ea-801f-b67c8d51e0b0.jpg)

The code of the table: https://demos.creative-tim.com/material-dashboard/docs/2.1/components/tables.html

Could you please help me? Thanks a lot.

**Comment by yzgan-bookdoc** [comment]
It should be working at erb. Just try to tally your erb with haml codes

what I observed is that in your `application.html.erb`, yield block might not be wrapped under `main-panel` div element without current user.

try to fix that and see if it work

**Comment by Louigi16** [comment]
This problem persists. 
I've also tried this, but there is the same problem:
1. Cloned this template as new project
2. Modified application.html.haml in application.html.erb without adding custom code. I just converted the code.
3. Copy and paste tables example from docs.

It works well with haml, but not with erb.

**Comment by yzgan-bookdoc** [comment]
I tried in erb and it works without problem. Change your doctype and remove the extra attributes

application.html.erb
```erb
<!DOCTYPE html>
```
